function OPZ_EditLimits( h , XYZC )

  if nargin == 2 && XYZC == 0
    delete( findobj(h ,'type','uicontrol','-and','-regexp','tag','OPZ_AXE_LIM_EDIT*') );
    lostfocus( h );
    return;
  end

  objs = findobj(h ,'type','uicontrol','-and','-regexp','tag','OPZ_AXE_LIM_EDIT*');
  if ~isempty( objs );
    for obj = objs(:)'
      ax = get( obj , 'UserData' );
      if ~ishandle(ax), continue; end
      switch get(obj,'Tag')
        case 'OPZ_AXE_LIM_EDIT_X1', lim = get( ax , 'XLim' ); lim = lim(1);
        case 'OPZ_AXE_LIM_EDIT_X2', lim = get( ax , 'XLim' ); lim = lim(2);
        case 'OPZ_AXE_LIM_EDIT_Y1', lim = get( ax , 'YLim' ); lim = lim(1);
        case 'OPZ_AXE_LIM_EDIT_Y2', lim = get( ax , 'YLim' ); lim = lim(2);
        case 'OPZ_AXE_LIM_EDIT_Z1', lim = get( ax , 'ZLim' ); lim = lim(1);
        case 'OPZ_AXE_LIM_EDIT_Z2', lim = get( ax , 'ZLim' ); lim = lim(2);
      end
      try, set( obj , 'string' , num2str( lim ) ); end
    end
    return;
  end


  axs = findall( h , 'Type','axes' );
  if numel(axs) && strcmp( get( h , 'ToolBar' ) , 'auto' ) && numel( findall(h,'Type','uicontrol') )
    set( h , 'Toolbar','Figure' );
  end
  
  for ax = axs(:)'
%     if is3daxes( ax ), continue; end
    if strcmpi( get(ax,'Tag') , 'colorbar' ), continue; end
    
    xl = get(ax,'XLim');
    yl = get(ax,'YLim');
    zl = get(ax,'ZLim');

    switch XYZC
      case 'X'
        ui_obj = uicontrol('style','edit','FontUnits','pixels','FontSize', 8,'UserData',ax,...
          'tag','OPZ_AXE_LIM_EDIT_X1' ,...
          'string' , num2str(xl(1))      ,...
          'BackgroundColor', [1 0.5 0.5] ,...
          'Position' , [axesxyz2figurexy( ax , [ xl(1) yl(1) zl(1) ] )-[30 8] 60 14]     ,...
          'callback',@(h,e) set_AXE_lim(h,ax,'XLim',1) ...
        );
%         ui_obj = handle2javaobject( ui_obj ); ui_obj = ui_obj(2); ui_obj = ui_obj{1};
%         set(ui_obj,'KeyPressedCallback',@(h,e) set( ui_obj,'Tex', strrep( get(ui_obj,'Tex'),' ','') ) )

        ui_obj = uicontrol('style','edit','FontUnits','pixels','FontSize', 8,'UserData',ax,...
          'tag','OPZ_AXE_LIM_EDIT_X2' ,...
          'string' , num2str(xl(2))      ,...
          'BackgroundColor', [1 0.5 0.5] ,...
          'Position' , [axesxyz2figurexy( ax , [ xl(2) yl(1) zl(1) ] )-[30 8] 60 14]     ,...
          'callback',@(h,e) set_AXE_lim(h,ax,'XLim',2) ...
        );
      
      case 'Y'
        ui_obj = uicontrol('style','edit','FontUnits','pixels','FontSize', 8,'UserData',ax,...
          'tag','OPZ_AXE_LIM_EDIT_Y1' ,...
          'string' , num2str(yl(1))      ,...
          'BackgroundColor', [0.5 1 0.5] ,...
          'Position' , [axesxyz2figurexy( ax , [ xl(1) yl(1) zl(1) ] )-[30 8] 60 14]     ,...
          'callback',@(h,e) set_AXE_lim(h,ax,'YLim',1) ...
        );

        ui_obj = uicontrol('style','edit','FontUnits','pixels','FontSize', 8,'UserData',ax,...
          'tag','OPZ_AXE_LIM_EDIT_Y2' ,...
          'string' , num2str(yl(2))      ,...
          'BackgroundColor', [0.5 1 0.5] ,...
          'Position' , [axesxyz2figurexy( ax , [ xl(1) yl(2) zl(1) ] )-[30 8] 60 14]     ,...
          'callback',@(h,e) set_AXE_lim(h,ax,'YLim',2) ...
        );

      case 'Z'    
        ui_obj = uicontrol('style','edit','FontUnits','pixels','FontSize', 8,'UserData',ax,...
          'tag','OPZ_AXE_LIM_EDIT_Z1' ,...
          'string' , num2str(zl(1))      ,...
          'BackgroundColor', [0.5 0.5 1] ,...
          'Position' , [axesxyz2figurexy( ax , [ xl(1) yl(1) zl(1) ] )-[30 8] 60 14]     ,...
          'callback',@(h,e) set_AXE_lim(h,ax,'ZLim',1) ...
        );

        ui_obj = uicontrol('style','edit','FontUnits','pixels','FontSize', 8,'UserData',ax,...
          'tag','OPZ_AXE_LIM_EDIT_Z2' ,...
          'string' , num2str(zl(2))      ,...
          'BackgroundColor', [0.5 0.5 1] ,...
          'Position' , [axesxyz2figurexy( ax , [ xl(1) yl(1) zl(2) ] )-[30 8] 60 14]     ,...
          'callback',@(h,e) set_AXE_lim(h,ax,'ZLim',2) ...
        );
    end
  end


  function set_AXE_lim(h,ax,x,i)
    try,
      val = str2num( get(h,'string') );
      lim = get(ax, x);
      lim(i) = val;
      set( ax , x , lim );
    end
    OPZ_EditLimits( gcf , 0 );
  end

end
